# Generated by Django 4.2.16 on 2025-12-04 14:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
