# Generated by Django 4.2.16 on 2025-12-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
